# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- azure-pipelines

pool:
  name: 'dasjoy-agent-pool'
  demands:
    - Agent.Name -equals agent2

stages:
- stage: build
  jobs:
  - job: build_application
    displayName: "Build Application"
    container:
      image: node:24-bullseye
    steps:
    - script: npm install
      displayName: "Install npm Dependencis"
    - script: npm audit || true
      displayName: "Asses vulnerability of npm Dependencis"
- stage: test
  jobs:
  - job: run_testcases
    displayName: "Run Testcases"
    container:
      image: node:24-bullseye
    steps:
    - script: npm install
      displayName: "Install npm Dependencis"
    - script: npm run test:coverage
      displayName: "run Testcases"
    - task: PublishPipelineArtifact@1
      inputs:
        artifact: coverage-report
        targetPath: "$(System.DefaultWorkingDirectory)/coverage"
    
  
  - job: covert_coverage_report
    displayName: "Convert Coverage Report"
    container:
      image: python:3.15.0b2-bookworm
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: 'coverage-report'
        path: '$(Pipeline.Workspace)/coverage'
    - script: |
        pip install lcov-cobertura --break-system-packages
        mkdir -p converted_report
        python3 lcov_cobertura.py coverage/lcov.info --output converted_report/cobertura-coverage.xml
    - task: PublishPipelineArtifact@1
      inputs:
        artifact: converted-report
        targetPath: converted_report

  - job: publish_coverage
    displayName: "Publish Coverage"
    dependsOn: run_testcases
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: 'converted-report'
        path: '$(Pipeline.Workspace)/converted_report'
    - script: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        export PATH="$PATH:$HOME/.dotnet/tools"
    - script: |
        ls -lR $(Pipeline.Workspace)/coverage
    - task: PublishCodeCoverageResults@2
      displayName: 'Publish Coverage to Azure UI'
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(Pipeline.Workspace)/converted_report/cobertura-coverage.xml'