# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- azure-pipelines

pool:
  name: 'dasjoy-agent-pool'
  demands:
    - Agent.Name -equals agent2

stages:
- stage: build
  jobs:
  - job: build_application
    displayName: "Build Application"
    container:
      image: node:24-alpine
    steps:
    - script: npm install
      displayName: "Install npm Dependencis"
    - script: npm audit
      displayName: "Asses vulnerability of npm Dependencis"
- stage: test
  jobs:
  - job: run_testcases
    displayName: "Run Testcases"
    container:
      image: node:24-alpine
    steps:
    - script: npm run test:coverage
      displayName: "run Testcases"
    - task: PublishCodeCoverageResults@2
      displayName: 'Publish Coverage to Azure UI'
      inputs:
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
    
